export const CLEAR_COURSE_DATA = 'CLEAR_COURSE_DATA';

export const DELETE_COURSE_START = 'DELETE_COURSE_START';
export const DELETE_COURSE_SUCCESS = 'DELETE_COURSE_SUCCESS';

export const ERROR = 'ERROR';
export const ERROR_CLEAR = 'ERROR_CLEAR';

export const FETCH_START = 'FETCH_START';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';

export const FETCH_ONE_START = 'FETCH_ONE_START';
export const FETCH_ONE_SUCCESS = 'FETCH_ONE_SUCCESS';

export const SAVE_COURSE_START = 'SAVE_COURSE_START';
export const SAVE_COURSE_SUCCESS = 'SAVE_COURSE_SUCCESS';
